Add LibreCounter stats
fastify/website pull request #167
Opened 2023-10-21 17:07 UTC by alexfernandez

## Description

Add stats for fastify.dev on [librecounter.org/fastify.dev/show](https://librecounter.org/fastify.dev/show). No cookies or tracking necessary. Please let me know if the chosen mode (hidden image) is appropriate, there are other [options](https://librecounter.org/options) and I can implement another style if needed. Thanks!

## Related Issues

Fixes https://github.com/fastify/website/issues/165.

## Check List

- [x] I have read the [Contributing Guidelines](./CONTRIBUTING.md)

2023-10-21 17:29 UTC, Eomm requested changes
Blocking for security reasons.
Integrating an external URL may be a vector of injection.

Thanks for PR, but if we go with this solution, we must deploy a https://github.com/alexfernandez/librecounter installation on our server.

2023-10-21 18:14 UTC, alexfernandez commented
Thanks for the review. I am a bit baffled though :thinking: May I ask what are the risks that you have in mind? It's not a script or an iframe: just an image tag `<img>` so only an image can be "injected", and also it is not shown on the page. As far as I know including external images should be more or less safe. After a [quick](https://meta.stackexchange.com/questions/55665/allowing-images-from-external-sources-opens-doors-to-serious-security-exploits-a) [search](https://stackoverflow.com/questions/13551372/security-concerns-of-embedding-a-third-party-image-in-html) I did not find major concerns, but I'm willing to be educated.

You can also see on [the original Docusaurus project](https://github.com/facebook/docusaurus/blob/45f1a669b5ab29a04365f20e88e37e085c0fb4de/website/docusaurus.config.ts#L683) that they similarly include an image from Netlify.

2023-10-21 18:16 UTC, alexfernandez commented
If going the path of installing LibreCounter on your servers, how would we proceed? I understand you are using GitHub pages and therefore using GitHub's servers, how can you install anything on them?

2023-10-21 19:03 UTC, Uzlopak commented
I am also not convinced of the GPDR conformancy claim. Yes it is true, that not storing personal data is not a GDPR issue. But the issues are more about transferring or relaying the personal information to third party sites without consent.

So if somebody visits fastify.dev, then it is a consentual interaction to process their IP and everything. In the moment we load external third-party resources, we force the visitor to also load the content and forcing to send the ip address to the third-party. 

Comparable to google fonts.

2023-10-21 19:15 UTC, alexfernandez commented
@Uzlopak Well, it is true that you have to verify that any resources included in the page are also GDPR-compliant to be GDPR-compliant yourself. You have full access to the [LibreCounter code](https://github.com/alexfernandez/librecounter/), but I might surreptitiously change it to do mildly evil things like store IP addresses and user agents; not a lot of harm but possible mischief. To counter this, I can give you limited access to the server if you want, so you can audit the running code at any time.

2023-10-21 19:26 UTC, Uzlopak commented
You dont store personal information and are gdpr conform. But by embedding the link to the external server which is loaded automatically with the image, we as the site owner need to get the consent of our visitor to send their data to your server. 

I actually wonder now if embedding the stars and fork buttons from github is gdpr conform or not.

2023-10-21 19:46 UTC, alexfernandez commented
@Uzlopak That is not how it works AFAIK: you need user consent to send any tracking info to third parties, but this is not what is done here.

The user is sending you their IP address and user agent, they get a webpage and then they instruct the browser to fetch all included images, so they are sending their IP address and user agent to other servers. The user may perfectly well not go to any other servers to fetch outside images. And as long as the third party server is invoked with a legitimate interest, as [seen e.g. here](https://law.stackexchange.com/a/31632), then you should be fine. But I would be happy to be proven wrong.

2023-10-21 19:56 UTC, alexfernandez commented
As another data point, I don't think you are requesting (or actually need) user consent for embedding images from `avatars.githubusercontent.com` in your home page:

```html
<img src="https://avatars.githubusercontent.com/u/5059100?v=4&amp;s=192" alt="Aras Abbasi's profile picture" width="96" height="96" loading="lazy">
```

The web would break in a million places if embedding external images was not possible!

2023-10-21 20:34 UTC, Uzlopak commented
Well, maybe we need consider to persist the avatars on our server instance.

2023-10-21 21:04 UTC, Uzlopak commented
Opened #168

2023-10-21 22:30 UTC, alexfernandez commented
That is a weird conclusion, and quite pointlessly hostile in my opinion. In any case I will withdraw my submission since it's not appreciated, let me know if you are interested in my little project at any point.

2023-10-21 22:30 UTC, closed without merging

2023-10-23 15:36 UTC, Uzlopak commented
@alexfernandez 

I dont know why you think that my conclusion would be hostile. I personally think your solution is awesome. But the GDPR aspect is for me not that clear, and your input was useful as it forces us to reconsider our gdpr conformancy as a whole.

2023-10-23 17:31 UTC, alexfernandez commented
OK, I understand your point of view better now. Sorry for jumping to conclusions. I would think that self-hosting all images is detrimental for the project and would be a non-optimal outcome of my PR, but if you are going that path regardless, then I will keep the PR open until it is resolved, hopefully by (rightfully) determining that external images are OK as long as they are justified.