5623: Add HeroDevs support banners to specific pages. Add new menu item.
fastify/website pull request #252
Opened 2024-10-04 20:20 UTC by AndreAngelantoni

## Description

This PR does the following:
- adds a new Support menu on the far right of the main navigation that points to the LTS page:

![screenshot_3501](https://github.com/user-attachments/assets/ba4349e8-8975-437d-8676-55f3b0585025)

- adds a new banner on the migration guides:

![screenshot_3502](https://github.com/user-attachments/assets/9f1810c7-69ed-49cd-93ec-17edff20b641)

- adds a new banner on versions of the documentation pages version 3 and lower:

![screenshot_3503](https://github.com/user-attachments/assets/d49a146f-e4a7-4897-a425-85257c5bf9bf)

The banners seemed to require swizzling the existing pages. If that wasn't correct, please advise.

## Related Issues

Addresses https://github.com/fastify/fastify/issues/5623.

## Check List
- [X] I have read the [Contributing Guidelines](./CONTRIBUTING.md)

2024-10-06 15:38 UTC, Eomm reviewed
Could you run the linter to get a green run&deploy?

```
/home/runner/work/website/website/src/theme/DocPage/index.js
Error:   79:10  error  'LatestVersionSuggestionLabel' is defined but never used  no-unused-vars
```

2024-10-07 16:54 UTC, AndreAngelantoni commented
Yes, will do.

On Sun, Oct 6, 2024 at 9:38 AM Manuel Spigolon ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Could you run the linter to get a green run&deploy?
>
> /home/runner/work/website/website/src/theme/DocPage/index.js
> Error:   79:10  error  'LatestVersionSuggestionLabel' is defined but never used  no-unused-vars
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fastify/website/pull/252#pullrequestreview-2350556289>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BE3WQBIPSKUN2RRWDSPNNIDZ2FKPFAVCNFSM6AAAAABPMRL5QSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNJQGU2TMMRYHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-09 19:41 UTC, Uzlopak commented
![image](https://github.com/user-attachments/assets/4c94b8cb-2329-4e0b-a9d6-1ec2b668f2dc)

2024-10-09 19:45 UTC, Uzlopak commented on src/theme/DocVersionBanner/index.js
> +/**
Why is that facebook copyright?

2024-10-10 00:39 UTC, AndreAngelantoni commented
Not part of our PR...sorry, couldn't tell you.

On Wed, Oct 9, 2024 at 1:45 PM Aras Abbasi ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/theme/DocVersionBanner/index.js
> <https://github.com/fastify/website/pull/252#discussion_r1794138464>:
>
> > @@ -0,0 +1,126 @@
> +/**
>
> Why is that facebook copyright?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fastify/website/pull/252#pullrequestreview-2358169946>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BE3WQBJWSB5D5NIRDGTCUVLZ2WBWHAVCNFSM6AAAAABPMRL5QSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNJYGE3DSOJUGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-10 07:39 UTC, mcollina commented
@AndreAngelantoni it's 100% part of your PR.

2024-10-10 13:02 UTC, AndreAngelantoni commented
Ok, I'll look into it.

On Thu, Oct 10, 2024 at 1:40 AM Matteo Collina ***@***.***>
wrote:

> @AndreAngelantoni <https://github.com/AndreAngelantoni> it's 100% part of
> your PR.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fastify/website/pull/252#issuecomment-2404315276>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BE3WQBMXEN63I3EHOIOGCYDZ2YVODAVCNFSM6AAAAABPMRL5QSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBUGMYTKMRXGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-11 18:35 UTC, AndreAngelantoni commented
My apologies, I thought that was for something else.

That was added by the Swizzler tool and has now been removed. Looking into the HTML detritus next.

2024-10-11 18:46 UTC, AndreAngelantoni commented
> ![image](https://private-user-images.githubusercontent.com/5059100/375108600-4c94b8cb-2329-4e0b-a9d6-1ec2b668f2dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NzI1MzMsIm5iZiI6MTcyODY3MjIzMywicGF0aCI6Ii81MDU5MTAwLzM3NTEwODYwMC00Yzk0YjhjYi0yMzI5LTRlMGItYTlkNi0xZWMyYjY2OGYyZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMTg0MzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQ0N2FmYWZhYmJlN2Q5ZmMwODYwN2RkMmIwMWNmOWQwZDQyOWRlMTM4NTU3MWIyZjczNDRmZmUzNDBmN2ViZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7IxHaLllPcLdycJROiIjZYKSuLwvDKeumOevNXHzk1k) ![image](https://private-user-images.githubusercontent.com/5059100/375108795-af57c7f8-54d5-406c-9684-e3df36e989dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NzI1MzMsIm5iZiI6MTcyODY3MjIzMywicGF0aCI6Ii81MDU5MTAwLzM3NTEwODc5NS1hZjU3YzdmOC01NGQ1LTQwNmMtOTY4NC1lM2RmMzZlOTg5ZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMTg0MzUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjcxY2VlODk0YzVjYTk5ZTczYTg2MTI0MjYxNjAzOTRjZmMzYWE1MDA2NmExMjIxNjBjM2FjNTg4MDNmZTNjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GIZOtxa7KCJBWuZeNko9SA5IW5xao1mV_F1rBqmHX10)

I'm seeing this extra HTML in the current production docs:
https://fastify.dev/docs/latest/Reference/LTS/

I can certainly remove it as part of this PR but perhaps someone had intentions for it? (This is what I thought the other comment was referring to. Again, my apologies.)

2024-10-15 13:25 UTC, mcollina requested changes
The banner should not be shown for v4, which is still supported.
Looks good otherwise.

<img width="729" alt="Screenshot 2024-10-15 at 15 23 19" src="https://github.com/user-attachments/assets/3c418c28-0ce7-4677-a0d2-9b6307808beb">

2024-10-15 17:31 UTC, AndreAngelantoni commented
My apologies...I thought the comment was referring to something else.

That was added by the Swizzler tool and it's now gone.

On Thu, Oct 10, 2024 at 7:02 AM André Angelantoni ***@***.***>
wrote:

> Ok, I'll look into it.
>
> On Thu, Oct 10, 2024 at 1:40 AM Matteo Collina ***@***.***>
> wrote:
>
>> @AndreAngelantoni <https://github.com/AndreAngelantoni> it's 100% part
>> of your PR.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/fastify/website/pull/252#issuecomment-2404315276>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BE3WQBMXEN63I3EHOIOGCYDZ2YVODAVCNFSM6AAAAABPMRL5QSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMBUGMYTKMRXGY>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-10-21 20:05 UTC, AndreAngelantoni commented
> The banner should not be shown for v4, which is still supported. Looks good otherwise.
> 

Modification made. Please confirm.

2024-12-06 08:23 UTC, Eomm commented
Could you update the branch so we can deploy to staging?

Feel free to ping me to speed up the merge!

2024-12-11 21:30 UTC, AndreAngelantoni commented
/recheck

2024-12-11 22:01 UTC, AndreAngelantoni commented
@Eomm happy to work with you :-)

I rebased and am getting errors both locally and with the PR check:
```
Error: Can't render static file for pathname "/docs/latest/"
Error: Can't render static file for pathname "/docs/latest/docs/"
Error: Can't render static file for pathname "/docs/latest/docs/Guides/"
```


And several more. Perhaps an issue with the Docusaurus update?

2024-12-18 10:20 UTC, Eomm commented
I think there are few merge conflicts TBH will check it in a week or so

2024-12-21 09:05 UTC, Eomm commented on src/theme/DocVersionBanner/index.js
> +import { useActivePlugin, useDocVersionSuggestions } from '@docusaurus/plugin-content-docs/client'
I think this code should be upgraded to docusaurus v3:

Locally I get:

<img width="1282" alt="image" src="https://github.com/user-attachments/assets/9924e04c-be0c-4e4b-a40e-cbfcd6a7afe2" />

Note that I rebased this PR to `main` and other PR are working; https://github.com/fastify/website/pull/264

2025-02-11 23:00 UTC, AndreAngelantoni commented on src/theme/DocVersionBanner/index.js
> +import { useActivePlugin, useDocVersionSuggestions } from '@docusaurus/plugin-content-docs/client'
@Eomm I've upgraded the code to work with v3. Back over to you :-)

2025-03-05 09:13 UTC, Eomm approved these changes
Since the PR is quite old, let's push it

I can see the `parseVersion` function is duplicated but I think we should ship it - I will clean it later

2025-03-21 12:00 UTC, mcollina approved these changes
lgtm

2025-03-21 12:00 UTC, merged